name: eyetracker
channels:
  - menpo
dependencies:
  - python = 3
  - numpy
  - opencv3
  - pyqt
  - h5py
  - pyqtgraph
  - pyyaml
  - matplotlib # this may not be required
  - pytest # this may not be required