# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Oct 08 10:57:57 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(694, 424)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/eye.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_pupil = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_pupil.setObjectName(_fromUtf8("groupBox_pupil"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_pupil)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_pupil_binary = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_binary.setObjectName(_fromUtf8("label_pupil_binary"))
        self.gridLayout_5.addWidget(self.label_pupil_binary, 0, 0, 1, 1)
        self.horizontalSlider_pupil_binary = QtGui.QSlider(self.groupBox_pupil)
        self.horizontalSlider_pupil_binary.setMinimum(100)
        self.horizontalSlider_pupil_binary.setMaximum(255)
        self.horizontalSlider_pupil_binary.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pupil_binary.setObjectName(_fromUtf8("horizontalSlider_pupil_binary"))
        self.gridLayout_5.addWidget(self.horizontalSlider_pupil_binary, 0, 1, 1, 1)
        self.label_pupil_binary_value = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_binary_value.setObjectName(_fromUtf8("label_pupil_binary_value"))
        self.gridLayout_5.addWidget(self.label_pupil_binary_value, 0, 2, 1, 1)
        self.label_pupil_min = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_min.setObjectName(_fromUtf8("label_pupil_min"))
        self.gridLayout_5.addWidget(self.label_pupil_min, 1, 0, 1, 1)
        self.horizontalSlider_pupil_min = QtGui.QSlider(self.groupBox_pupil)
        self.horizontalSlider_pupil_min.setMinimum(10)
        self.horizontalSlider_pupil_min.setMaximum(4000)
        self.horizontalSlider_pupil_min.setProperty("value", 99)
        self.horizontalSlider_pupil_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pupil_min.setObjectName(_fromUtf8("horizontalSlider_pupil_min"))
        self.gridLayout_5.addWidget(self.horizontalSlider_pupil_min, 1, 1, 1, 1)
        self.label_pupil_min_value = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_min_value.setObjectName(_fromUtf8("label_pupil_min_value"))
        self.gridLayout_5.addWidget(self.label_pupil_min_value, 1, 2, 1, 1)
        self.label_pupil_max = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_max.setObjectName(_fromUtf8("label_pupil_max"))
        self.gridLayout_5.addWidget(self.label_pupil_max, 2, 0, 1, 1)
        self.horizontalSlider_pupil_mask_circle = QtGui.QSlider(self.groupBox_pupil)
        self.horizontalSlider_pupil_mask_circle.setMinimum(1)
        self.horizontalSlider_pupil_mask_circle.setMaximum(100)
        self.horizontalSlider_pupil_mask_circle.setProperty("value", 39)
        self.horizontalSlider_pupil_mask_circle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pupil_mask_circle.setObjectName(_fromUtf8("horizontalSlider_pupil_mask_circle"))
        self.gridLayout_5.addWidget(self.horizontalSlider_pupil_mask_circle, 2, 1, 1, 1)
        self.label_pupil_mask_value = QtGui.QLabel(self.groupBox_pupil)
        self.label_pupil_mask_value.setObjectName(_fromUtf8("label_pupil_mask_value"))
        self.gridLayout_5.addWidget(self.label_pupil_mask_value, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_pupil, 1, 1, 1, 1)
        self.groupBox_general = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_general.setObjectName(_fromUtf8("groupBox_general"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_general)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_general_blur = QtGui.QLabel(self.groupBox_general)
        self.label_general_blur.setObjectName(_fromUtf8("label_general_blur"))
        self.gridLayout_2.addWidget(self.label_general_blur, 1, 0, 1, 1)
        self.horizontalSlider_general_blur = QtGui.QSlider(self.groupBox_general)
        self.horizontalSlider_general_blur.setMinimum(1)
        self.horizontalSlider_general_blur.setMaximum(10)
        self.horizontalSlider_general_blur.setProperty("value", 1)
        self.horizontalSlider_general_blur.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_general_blur.setObjectName(_fromUtf8("horizontalSlider_general_blur"))
        self.gridLayout_2.addWidget(self.horizontalSlider_general_blur, 1, 1, 1, 1)
        self.label_general_dilation = QtGui.QLabel(self.groupBox_general)
        self.label_general_dilation.setObjectName(_fromUtf8("label_general_dilation"))
        self.gridLayout_2.addWidget(self.label_general_dilation, 2, 2, 1, 1)
        self.label_general_blur_2 = QtGui.QLabel(self.groupBox_general)
        self.label_general_blur_2.setObjectName(_fromUtf8("label_general_blur_2"))
        self.gridLayout_2.addWidget(self.label_general_blur_2, 2, 0, 1, 1)
        self.label_general_erosion = QtGui.QLabel(self.groupBox_general)
        self.label_general_erosion.setObjectName(_fromUtf8("label_general_erosion"))
        self.gridLayout_2.addWidget(self.label_general_erosion, 0, 2, 1, 1)
        self.horizontalSlider_general_erosion = QtGui.QSlider(self.groupBox_general)
        self.horizontalSlider_general_erosion.setMaximum(10)
        self.horizontalSlider_general_erosion.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_general_erosion.setObjectName(_fromUtf8("horizontalSlider_general_erosion"))
        self.gridLayout_2.addWidget(self.horizontalSlider_general_erosion, 0, 1, 1, 1)
        self.label_general_blur_3 = QtGui.QLabel(self.groupBox_general)
        self.label_general_blur_3.setObjectName(_fromUtf8("label_general_blur_3"))
        self.gridLayout_2.addWidget(self.label_general_blur_3, 0, 0, 1, 1)
        self.label_general_blur_value = QtGui.QLabel(self.groupBox_general)
        self.label_general_blur_value.setObjectName(_fromUtf8("label_general_blur_value"))
        self.gridLayout_2.addWidget(self.label_general_blur_value, 1, 2, 1, 1)
        self.horizontalSlider_general_dilation = QtGui.QSlider(self.groupBox_general)
        self.horizontalSlider_general_dilation.setMaximum(10)
        self.horizontalSlider_general_dilation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_general_dilation.setObjectName(_fromUtf8("horizontalSlider_general_dilation"))
        self.gridLayout_2.addWidget(self.horizontalSlider_general_dilation, 2, 1, 1, 1)
        self.checkBox_equalize = QtGui.QCheckBox(self.groupBox_general)
        self.checkBox_equalize.setObjectName(_fromUtf8("checkBox_equalize"))
        self.gridLayout_2.addWidget(self.checkBox_equalize, 3, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_general, 0, 1, 1, 1)
        self.groupBox_led = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_led.setObjectName(_fromUtf8("groupBox_led"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_led)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_led_binary = QtGui.QLabel(self.groupBox_led)
        self.label_led_binary.setObjectName(_fromUtf8("label_led_binary"))
        self.gridLayout_4.addWidget(self.label_led_binary, 0, 0, 1, 1)
        self.horizontalSlider_led_binary = QtGui.QSlider(self.groupBox_led)
        self.horizontalSlider_led_binary.setMinimum(100)
        self.horizontalSlider_led_binary.setMaximum(255)
        self.horizontalSlider_led_binary.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_binary.setObjectName(_fromUtf8("horizontalSlider_led_binary"))
        self.gridLayout_4.addWidget(self.horizontalSlider_led_binary, 0, 1, 1, 1)
        self.label_led_binary_value = QtGui.QLabel(self.groupBox_led)
        self.label_led_binary_value.setObjectName(_fromUtf8("label_led_binary_value"))
        self.gridLayout_4.addWidget(self.label_led_binary_value, 0, 2, 1, 1)
        self.label_led_min = QtGui.QLabel(self.groupBox_led)
        self.label_led_min.setObjectName(_fromUtf8("label_led_min"))
        self.gridLayout_4.addWidget(self.label_led_min, 1, 0, 1, 1)
        self.horizontalSlider_led_min = QtGui.QSlider(self.groupBox_led)
        self.horizontalSlider_led_min.setMinimum(1)
        self.horizontalSlider_led_min.setMaximum(200)
        self.horizontalSlider_led_min.setProperty("value", 2)
        self.horizontalSlider_led_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_min.setObjectName(_fromUtf8("horizontalSlider_led_min"))
        self.gridLayout_4.addWidget(self.horizontalSlider_led_min, 1, 1, 1, 1)
        self.label_led_min_value = QtGui.QLabel(self.groupBox_led)
        self.label_led_min_value.setObjectName(_fromUtf8("label_led_min_value"))
        self.gridLayout_4.addWidget(self.label_led_min_value, 1, 2, 1, 1)
        self.label_led_max = QtGui.QLabel(self.groupBox_led)
        self.label_led_max.setObjectName(_fromUtf8("label_led_max"))
        self.gridLayout_4.addWidget(self.label_led_max, 2, 0, 1, 1)
        self.horizontalSlider_led_mask_circle = QtGui.QSlider(self.groupBox_led)
        self.horizontalSlider_led_mask_circle.setMinimum(1)
        self.horizontalSlider_led_mask_circle.setMaximum(100)
        self.horizontalSlider_led_mask_circle.setProperty("value", 4)
        self.horizontalSlider_led_mask_circle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_mask_circle.setObjectName(_fromUtf8("horizontalSlider_led_mask_circle"))
        self.gridLayout_4.addWidget(self.horizontalSlider_led_mask_circle, 2, 1, 1, 1)
        self.label_led_mask_value = QtGui.QLabel(self.groupBox_led)
        self.label_led_mask_value.setObjectName(_fromUtf8("label_led_mask_value"))
        self.gridLayout_4.addWidget(self.label_led_mask_value, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_led, 1, 0, 1, 1)
        self.groupBox_Output = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Output.setObjectName(_fromUtf8("groupBox_Output"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_Output)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_saveConfig = QtGui.QPushButton(self.groupBox_Output)
        self.pushButton_saveConfig.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_saveConfig.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_saveConfig.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/save_config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_saveConfig.setIcon(icon1)
        self.pushButton_saveConfig.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_saveConfig.setObjectName(_fromUtf8("pushButton_saveConfig"))
        self.gridLayout.addWidget(self.pushButton_saveConfig, 0, 1, 1, 1)
        self.pushButton_pauseplay = QtGui.QPushButton(self.groupBox_Output)
        self.pushButton_pauseplay.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_pauseplay.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_pauseplay.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("res/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pauseplay.setIcon(icon2)
        self.pushButton_pauseplay.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_pauseplay.setObjectName(_fromUtf8("pushButton_pauseplay"))
        self.gridLayout.addWidget(self.pushButton_pauseplay, 0, 0, 1, 1)
        self.pushButton_process = QtGui.QPushButton(self.groupBox_Output)
        self.pushButton_process.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_process.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_process.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("res/process.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_process.setIcon(icon3)
        self.pushButton_process.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_process.setObjectName(_fromUtf8("pushButton_process"))
        self.gridLayout.addWidget(self.pushButton_process, 0, 3, 1, 1)
        self.pushButton_loadConfig = QtGui.QPushButton(self.groupBox_Output)
        self.pushButton_loadConfig.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_loadConfig.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_loadConfig.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/load_config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_loadConfig.setIcon(icon4)
        self.pushButton_loadConfig.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_loadConfig.setObjectName(_fromUtf8("pushButton_loadConfig"))
        self.gridLayout.addWidget(self.pushButton_loadConfig, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Output, 2, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.checkBox_markup = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_markup.setChecked(True)
        self.checkBox_markup.setObjectName(_fromUtf8("checkBox_markup"))
        self.gridLayout_9.addWidget(self.checkBox_markup, 0, 0, 1, 1)
        self.checkBox_showProcessing = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_showProcessing.setChecked(False)
        self.checkBox_showProcessing.setObjectName(_fromUtf8("checkBox_showProcessing"))
        self.gridLayout_9.addWidget(self.checkBox_showProcessing, 1, 0, 1, 1)
        self.comboBox_processing = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_processing.setObjectName(_fromUtf8("comboBox_processing"))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.comboBox_processing.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_processing, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_fpstext = QtGui.QLabel(self.groupBox_3)
        self.label_fpstext.setObjectName(_fromUtf8("label_fpstext"))
        self.gridLayout_10.addWidget(self.label_fpstext, 0, 0, 1, 1)
        self.label_azimuth = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_azimuth.setFont(font)
        self.label_azimuth.setObjectName(_fromUtf8("label_azimuth"))
        self.gridLayout_10.addWidget(self.label_azimuth, 4, 1, 1, 1)
        self.label_azimuthtext = QtGui.QLabel(self.groupBox_3)
        self.label_azimuthtext.setObjectName(_fromUtf8("label_azimuthtext"))
        self.gridLayout_10.addWidget(self.label_azimuthtext, 4, 0, 1, 1)
        self.label_fps = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_fps.setFont(font)
        self.label_fps.setObjectName(_fromUtf8("label_fps"))
        self.gridLayout_10.addWidget(self.label_fps, 0, 1, 1, 1)
        self.label_zenith = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_zenith.setFont(font)
        self.label_zenith.setObjectName(_fromUtf8("label_zenith"))
        self.gridLayout_10.addWidget(self.label_zenith, 5, 1, 1, 1)
        self.label_zenithtext = QtGui.QLabel(self.groupBox_3)
        self.label_zenithtext.setObjectName(_fromUtf8("label_zenithtext"))
        self.gridLayout_10.addWidget(self.label_zenithtext, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_10.addWidget(self.label_3, 8, 0, 1, 1)
        self.label_ledPosition = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_ledPosition.setFont(font)
        self.label_ledPosition.setObjectName(_fromUtf8("label_ledPosition"))
        self.gridLayout_10.addWidget(self.label_ledPosition, 8, 1, 1, 1)
        self.label_pupiltext = QtGui.QLabel(self.groupBox_3)
        self.label_pupiltext.setObjectName(_fromUtf8("label_pupiltext"))
        self.gridLayout_10.addWidget(self.label_pupiltext, 2, 0, 1, 1)
        self.label_pupil_area = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_pupil_area.setFont(font)
        self.label_pupil_area.setObjectName(_fromUtf8("label_pupil_area"))
        self.gridLayout_10.addWidget(self.label_pupil_area, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 1)
        self.label_pupilPosition = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_pupilPosition.setFont(font)
        self.label_pupilPosition.setObjectName(_fromUtf8("label_pupilPosition"))
        self.gridLayout_10.addWidget(self.label_pupilPosition, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad = QtGui.QMenu(self.menuFile)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("res/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLoad.setIcon(icon5)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuSave_2 = QtGui.QMenu(self.menuFile)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("res/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSave_2.setIcon(icon6)
        self.menuSave_2.setObjectName(_fromUtf8("menuSave_2"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.action_load_movie = QtGui.QAction(MainWindow)
        self.action_load_movie.setObjectName(_fromUtf8("action_load_movie"))
        self.action_load_hdf5 = QtGui.QAction(MainWindow)
        self.action_load_hdf5.setObjectName(_fromUtf8("action_load_hdf5"))
        self.actionAvi = QtGui.QAction(MainWindow)
        self.actionAvi.setObjectName(_fromUtf8("actionAvi"))
        self.actionTiff_stack = QtGui.QAction(MainWindow)
        self.actionTiff_stack.setObjectName(_fromUtf8("actionTiff_stack"))
        self.actionPlots = QtGui.QAction(MainWindow)
        self.actionPlots.setObjectName(_fromUtf8("actionPlots"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.action_save_avi = QtGui.QAction(MainWindow)
        self.action_save_avi.setObjectName(_fromUtf8("action_save_avi"))
        self.action_save_hdf5 = QtGui.QAction(MainWindow)
        self.action_save_hdf5.setObjectName(_fromUtf8("action_save_hdf5"))
        self.action_save_tiff = QtGui.QAction(MainWindow)
        self.action_save_tiff.setObjectName(_fromUtf8("action_save_tiff"))
        self.action_load_tiff = QtGui.QAction(MainWindow)
        self.action_load_tiff.setObjectName(_fromUtf8("action_load_tiff"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionModel = QtGui.QAction(MainWindow)
        self.actionModel.setObjectName(_fromUtf8("actionModel"))
        self.action_custom_algorithm = QtGui.QAction(MainWindow)
        self.action_custom_algorithm.setObjectName(_fromUtf8("action_custom_algorithm"))
        self.actionVideo = QtGui.QAction(MainWindow)
        self.actionVideo.setObjectName(_fromUtf8("actionVideo"))
        self.menuLoad.addAction(self.action_load_movie)
        self.menuLoad.addAction(self.action_load_hdf5)
        self.menuLoad.addAction(self.action_load_tiff)
        self.menuLoad.addSeparator()
        self.menuLoad.addAction(self.action_custom_algorithm)
        self.menuSave_2.addAction(self.action_save_avi)
        self.menuSave_2.addAction(self.action_save_hdf5)
        self.menuSave_2.addAction(self.action_save_tiff)
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuSave_2.menuAction())
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionVideo)
        self.menuView.addAction(self.actionPlots)
        self.menuView.addAction(self.actionModel)
        self.menuView.addAction(self.actionSettings)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.horizontalSlider_led_binary, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_led_binary_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_led_mask_circle, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_led_mask_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_led_min, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_led_min_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_general_blur, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_general_blur_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_pupil_binary, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_pupil_binary_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_pupil_mask_circle, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_pupil_mask_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_pupil_min, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_pupil_min_value.setNum)
        QtCore.QObject.connect(self.horizontalSlider_general_dilation, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_general_dilation.setNum)
        QtCore.QObject.connect(self.horizontalSlider_general_erosion, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_general_erosion.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Eyetracker", None))
        self.groupBox_pupil.setTitle(_translate("MainWindow", "Pupil", None))
        self.label_pupil_binary.setText(_translate("MainWindow", "Binary Thresh", None))
        self.label_pupil_binary_value.setText(_translate("MainWindow", "0.0", None))
        self.label_pupil_min.setText(_translate("MainWindow", "Min Size", None))
        self.label_pupil_min_value.setText(_translate("MainWindow", "0.0", None))
        self.label_pupil_max.setText(_translate("MainWindow", "Mask Circle", None))
        self.label_pupil_mask_value.setText(_translate("MainWindow", "0.0", None))
        self.groupBox_general.setTitle(_translate("MainWindow", "General", None))
        self.label_general_blur.setText(_translate("MainWindow", "Blur", None))
        self.label_general_dilation.setText(_translate("MainWindow", "0", None))
        self.label_general_blur_2.setText(_translate("MainWindow", "Dilation", None))
        self.label_general_erosion.setText(_translate("MainWindow", "0", None))
        self.label_general_blur_3.setText(_translate("MainWindow", "Erosion", None))
        self.label_general_blur_value.setText(_translate("MainWindow", "0", None))
        self.checkBox_equalize.setText(_translate("MainWindow", "Equalize Histogram", None))
        self.groupBox_led.setTitle(_translate("MainWindow", "LED", None))
        self.label_led_binary.setText(_translate("MainWindow", "Binary Thresh", None))
        self.label_led_binary_value.setText(_translate("MainWindow", "0.0", None))
        self.label_led_min.setText(_translate("MainWindow", "Min Size", None))
        self.label_led_min_value.setText(_translate("MainWindow", "0.0", None))
        self.label_led_max.setText(_translate("MainWindow", "Mask Circle", None))
        self.label_led_mask_value.setText(_translate("MainWindow", "0.0", None))
        self.groupBox_Output.setTitle(_translate("MainWindow", "Output", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Display", None))
        self.checkBox_markup.setText(_translate("MainWindow", "Image markup", None))
        self.checkBox_showProcessing.setText(_translate("MainWindow", "Show Processing", None))
        self.comboBox_processing.setItemText(0, _translate("MainWindow", "pupil_binary", None))
        self.comboBox_processing.setItemText(1, _translate("MainWindow", "led_binary", None))
        self.comboBox_processing.setItemText(2, _translate("MainWindow", "pupil_region", None))
        self.comboBox_processing.setItemText(3, _translate("MainWindow", "led_region", None))
        self.comboBox_processing.setItemText(4, _translate("MainWindow", "eroded", None))
        self.comboBox_processing.setItemText(5, _translate("MainWindow", "edges", None))
        self.comboBox_processing.setItemText(6, _translate("MainWindow", "combined", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Details", None))
        self.label_fpstext.setText(_translate("MainWindow", "FPS:", None))
        self.label_azimuth.setText(_translate("MainWindow", "0", None))
        self.label_azimuthtext.setText(_translate("MainWindow", "Azimuth:", None))
        self.label_fps.setText(_translate("MainWindow", "0", None))
        self.label_zenith.setText(_translate("MainWindow", "0", None))
        self.label_zenithtext.setText(_translate("MainWindow", "Zenith:", None))
        self.label_3.setText(_translate("MainWindow", "LED Position:", None))
        self.label_ledPosition.setText(_translate("MainWindow", "0", None))
        self.label_pupiltext.setText(_translate("MainWindow", "Pupil Area:", None))
        self.label_pupil_area.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "Pupil Position:", None))
        self.label_pupilPosition.setText(_translate("MainWindow", "0", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuLoad.setTitle(_translate("MainWindow", "Load", None))
        self.menuSave_2.setTitle(_translate("MainWindow", "Save", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.action_load_movie.setText(_translate("MainWindow", "movie", None))
        self.action_load_hdf5.setText(_translate("MainWindow", "hdf5", None))
        self.actionAvi.setText(_translate("MainWindow", "avi", None))
        self.actionTiff_stack.setText(_translate("MainWindow", "hdf5", None))
        self.actionPlots.setText(_translate("MainWindow", "Plots", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.action_save_avi.setText(_translate("MainWindow", "avi", None))
        self.action_save_hdf5.setText(_translate("MainWindow", "hdf5", None))
        self.action_save_tiff.setText(_translate("MainWindow", "tiff stack", None))
        self.action_load_tiff.setText(_translate("MainWindow", "tiff stack", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionModel.setText(_translate("MainWindow", "Model", None))
        self.action_custom_algorithm.setText(_translate("MainWindow", "custom algorithm", None))
        self.actionVideo.setText(_translate("MainWindow", "Video", None))

